# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-10-15 11:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dailylog', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='performance',
            unique_together=set([('owner_type', 'owner_id', 'user')]),
        ),
    ]
