# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2022-10-21 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailylog', '0002_auto_20201015_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='metics',
            field=models.CharField(db_index=True, max_length=128, verbose_name='\u6307\u6807'),
        ),
    ]
